Homework5
Valerii-Kukharchuk/find-movie pull request #1
Opened 2017-05-17 16:52 UTC by Valerii-Kukharchuk

1. added Header comp-t
2. added SearchInput comp-t
3. Search comp-t was moved into Header then
4. It seems everything is done

2017-05-17 17:31 UTC, fullstackdb requested changes

2017-05-17 17:31 UTC, fullstackdb commented on src/app/app.component.ts
>    selector: 'app-root',
видаліть невикористовувану змінну `title`

2017-05-17 17:31 UTC, fullstackdb commented on src/app/services/film.service.ts
> +  searchEvent: EventEmitter<any> = new EventEmitter();
цікавий варіант взаємодії між компонентами.
Проте в Angular2 підтримується парадигма реактивного програмування. 
Необхідно працювати через `Subject` [документація](https://angular.io/docs/ts/latest/cookbook/component-communication.html) - пункт `Parent and children communicate via a service` [стаття](http://jasonwatmore.com/post/2016/12/01/angular-2-communicating-between-components-with-observable-subject)

2017-05-17 17:31 UTC, fullstackdb commented on src/app/header/header.component.ts
> +  ngOnInit() {
не використовується хук `ngOnInit()`
необхідно видалити

2017-05-17 17:31 UTC, fullstackdb commented on src/app/film-search/film-search.component.ts
> +  onSearch() {
некоректний варіант роботи з даними
необхідно використати Subject
деталі в коментарі до сервісу

2017-05-17 17:31 UTC, fullstackdb commented on src/app/header/header.component.html
> +  <!--<span>There wil be something new soon</span>-->
необхідно видалити коментарі

2017-05-17 17:31 UTC, fullstackdb commented on src/app/film-cards/film-cards.component.ts
> +      f => this.films.push(f)
використати TS, задати який саме тип передається і очікується
``` 
startSearchText: string
(films: Film[]) => {
     this.films = films;
}
```

перемістити змінну films в зону компонента
перемістити роботу з сервісом в хук ngOnInit
[стаття про хуки](https://medium.com/front-end-hacking/angular-2-component-lifecycle-hooks-fa5a84b4b64d)

2017-05-17 17:31 UTC, fullstackdb commented on src/app/film-cards/film-cards.component.ts
> +    this.service.searchEvent
переписати роботу з отриманням/передаванням даних в реактивний варіант.
Детальніше в коментарі в сервісі

2017-05-17 19:32 UTC, Valerii-Kukharchuk commented on src/app/app.component.ts
>    selector: 'app-root',
fixed

2017-05-17 19:33 UTC, Valerii-Kukharchuk commented on src/app/header/header.component.ts
> +  ngOnInit() {
fixed

2017-05-17 19:34 UTC, Valerii-Kukharchuk commented on src/app/header/header.component.html
> +  <!--<span>There wil be something new soon</span>-->
fixed

2017-05-19 16:40 UTC, Valerii-Kukharchuk commented on src/app/film-cards/film-cards.component.ts
> +      f => this.films.push(f)
fixed

2017-05-19 20:05 UTC, Valerii-Kukharchuk commented on src/app/film-search/film-search.component.ts
> +  onSearch() {
fixed. it is made through the Subject now

2017-05-19 20:14 UTC, Valerii-Kukharchuk commented
everything is fixed. please review again

2017-05-23 05:56 UTC, Valerii-Kukharchuk reviewed
review my pull-request again please

2017-06-07 19:59 UTC, fullstackdb approved these changes

2017-06-08 06:33 UTC, merged