added the finished homework #8. In order to run the homework and chec…
Valerii-Kukharchuk/find-movie pull request #2
Opened 2017-05-22 18:37 UTC by Valerii-Kukharchuk

…k it just open homework8/public/index.html in any browser. but it has checked only in Chrome

2017-05-24 10:29 UTC, ghost requested changes

2017-05-24 10:29 UTC, captainkovalsky commented on homework8/public/js/controller.js
> +        model.getData(searchText).then((data) => {
data переименовать

2017-05-24 10:29 UTC, captainkovalsky commented on homework8/public/js/controller.js
> +        gallery = new Gallery(data);
data переименовать

2017-05-25 19:26 UTC, Valerii-Kukharchuk commented on homework8/public/js/controller.js
> +        gallery = new Gallery(data);
fixed

2017-05-25 19:26 UTC, Valerii-Kukharchuk commented on homework8/public/js/controller.js
> +        model.getData(searchText).then((data) => {
fixed

2017-06-07 19:59 UTC, fullstackdb approved these changes

2017-06-08 08:22 UTC, merged