Homework10 1
Valerii-Kukharchuk/find-movie pull request #5
Opened 2017-06-08 13:01 UTC by Valerii-Kukharchuk

please review my code. it's about tasks with 'stars'

2017-06-13 20:31 UTC, ghost requested changes
Мелкие изменения

2017-06-13 20:31 UTC, captainkovalsky commented on src/app/film-list/film-list.component.html
> +  <a md-mini-fab href="#top"><md-icon>arrow_upward</md-icon></a>
@Valerii-Kukharchuk При пустом респонзе когда фильмы не найдены тоже показивается кнопка
Рекомендация попробуйте создать директиву(Attribute Directives) которая будет показывать кнопку если был скролл
Так-же компоненту с кнопкой go-up-btn где будет переиспользоваться директива 
Вот пример Attribute Directives https://gist.github.com/captainkovalsky/0c4da02038f881695ed7330e718883bb#file-scroll-directive-ts

2017-06-14 19:14 UTC, Valerii-Kukharchuk commented on src/app/film-list/film-list.component.html
> +  <a md-mini-fab href="#top"><md-icon>arrow_upward</md-icon></a>
it is made a directive to show or hide a DOM element when is scrolling.
the directive was done on base of your example. thanks for that!

2017-06-21 07:17 UTC, ghost approved these changes
good

2017-06-21 18:33 UTC, merged